### ISSUE TITLE
Adding Geta.EPi.Payments.Netaxept.CommerceManager to commerce manager does not give parameters section

### ISSUE THREAD

**Issue by gatisb** [Geta/EPi.Commerce.Payments#29]
Adding new payment method
![image](https://user-images.githubusercontent.com/1835493/27225072-37a56f18-52a1-11e7-8ca3-ad361f40bc58.png)

no parameters:
![image](https://user-images.githubusercontent.com/1835493/27225076-3dddb660-52a1-11e7-87c3-40a2d658e0f6.png)

- web.config.install.xdt is applied correctly

- this is copied in correct place as well: 

https://github.com/Geta/EPi.Commerce.Payments/tree/master/Netaxept/src/Geta.EPi.Payments.Netaxept.CommerceManager/Apps/Order/Payments/Plugins/Netaxept

![image](https://user-images.githubusercontent.com/1835493/27225143-8b9f4364-52a1-11e7-8abb-8f01badeca45.png)

**Comment by gatisb** [comment]
Versions: Geta.Epi.Commerce.Payments.Netaxept.Checkout" version="0.1.22"Geta.EPi.Payments.Netaxept.CommerceManager" version="0.1.22" targetFramework="net452" />

**Comment by gatisb** [comment]
@marijorg what could be the problem? are instructions missing something?
used these instructions: https://github.com/Geta/EPi.Commerce.Payments/blob/master/Netaxept/README.md

**Comment by patkleef** [comment]
@gatisb think you need to use netaxept as system keyword. EPiServer is using the system keyword to find the usercontrol on disk: Apps\Order\Payments\Plugins\**Netaxept**\ConfigurePayment.ascx

I'll update the documentation

**Comment by gatisb** [comment]
Thank you, its a bit of a problem, but I can change directory name and that works.
